### ISSUE TITLE
Missing [[maybe_unused]] 

### ISSUE THREAD

**Issue by staffantj** [bloomberg/p1160#13]
test_resource.cpp:297 is missing a [[maybe_unused]] on the alignment parameter due to the alignment check being commented out. Having to report via mobile so cannot do pull_request easily, sorry.

**Comment by cppguru** [comment]
Hm.  github sent me no notification about this issue.  I will look into it.

**Comment by cppguru** [comment]
Issue confirmed.  i will have to check if all intended compilers actually support that attribute before adding it.

**Comment by jwakely** [comment]
> Issue confirmed. i will have to check if all intended compilers actually support that attribute before adding it.

That's what `__has_cpp_attribute(maybe_unused)` is for.

**Comment by cppguru** [comment]
On compilers that support that, yes.  Since the accompanying proposal was stopped from being proposed this code in this repository will have to remain as it is,

**Comment by jwakely** [comment]
> On compilers that support that, yes.

That's what `#ifdef __has_cpp_attribute` is for.
