### ISSUE TITLE
Do not add to std::pmr

### ISSUE THREAD

**Issue by jwakely** [bloomberg/p1160#17]
Since this isn't in the standard, and the proposal to add it was rejected, it should not be in `std::pmr`.

The response from the committee was that it's useful as a third-party library but isn't needed in the standard. But this third-party library has undefined behaviour due to adding things to namespace `std`. It would be more useful as a third-party library if it didn't have undefined behaviour.

**Comment by cppguru** [comment]
It is not a third party library, but a demonstration of P1160.  If at the
time I presented it I would have been *actually* allowed to finish my
presentation it would have been clear.

The repository also has a readme that says: This repository contains the
source code and build system for an ***example implementation*** of a
std::pmr compatible polymorphic memory resource, intended for use in
instrumented tests. The paper which describes the motivation, operation,
and other aspects of this code can be found in the WG21 paper repository.

Its ***name*** is P1160, quite clearly showing that it belongs to that
paper.  The paper has not presented a final proposal but the closest to
what has been in use, and acknowledged that rethinking using the now
available language features (such as lambdas) is the next step.  This would
also have been clear if I weren't gagged after 12% of my presentation that
I was forced to create at the last minute (working overtime for days), then
not allowed to present.  After my time being moved several times until my
co-presenter (Alisdair) could not be there.

I think that from what has happened in San Diego the description that "it
(the proposal) was rejected" does not ring as an exact description.  What
really happened was that **presenting** the proposal was rejected by
extreme prejudice, which essentially broke the number one ISO rule that
everyone must be heard.  The comments in the room made it clear that it was
not the proposal that was rejected but false assumptions about it.  Also
the exact comment (I wonder if it is in the minutes) "I do not want to hear
anything about allocators" was uttered, showing extreme prejudice.  I would
love not to be reminded of that time, especially not in this manner.  There
are reasons that I am not anymore involved in WG21, or much of anything,
and that 5-10 minutes of (IMO undeserved) humiliation is a big part of it.
I would appreciate that if someone asks about that repository they would be
told to contact me directly, or Bloomberg LP if I am not available.

I disagree that example code for a C++ library proposal paper should not be
in `std::pmr`.

I am going to update the description to make sure that this is not a
library to be used ***as it is***, it is just code that accompanies the
paper and the presentation.

Attila

**Comment by jwakely** [comment]
So then there's no implementation of this feature that people can use in their own code without breaking the rules of the standard?

The difficult part is not "adding something to `std::pmr`" so there's not really any need to demonstrate that's possible. Making it usable as a third party library might actually be useful though.

**Comment by cppguru** [comment]
[BDE](https://github.com/bloomberg/bde/blob/main/groups/bsl/bslma/bslma_testallocator.h) is the open source library that Bloomberg offers.  This is a repository created *solely* as support for the gagged ISO proposal, and the purpose of that was to continue giving people the parts what make `std::pmr` useful.  As that will not happen as it seems, there is no interest to pursue the avenue represented by this code.  If the proposal would have been allowed to be presented and work on turning its API into a modern API for `std::pmr` encouraged my employer would have given the resources, at the time, to create a portable and no-strings-attached open source licensed implementation.  That train has sailed. :(

I am not a lawyer, but given the license of the sources in this repository anyone can take it and run with it, change it in any way they see fit.  I cannot.
